-- DROP TABLE IF EXISTS team_lineup CASCADE;
-- DROP TABLE IF EXISTS lineup CASCADE;
-- DROP TABLE IF EXISTS player CASCADE;
-- DROP TABLE IF EXISTS card CASCADE;
-- DROP TABLE IF EXISTS position CASCADE;
-- DROP TABLE IF EXISTS team_manager CASCADE;
-- DROP TABLE IF EXISTS match CASCADE;
-- DROP TABLE IF EXISTS season_match CASCADE;
-- DROP TABLE IF EXISTS team CASCADE;
-- DROP TABLE IF EXISTS stadium CASCADE;
-- DROP TABLE IF EXISTS referee CASCADE;
-- DROP TABLE IF EXISTS competition CASCADE;
-- DROP TABLE IF EXISTS manager CASCADE;
-- DROP TABLE IF EXISTS season CASCADE;
-- DROP TABLE IF EXISTS competition_season CASCADE;
-- DROP TABLE IF EXISTS event CASCADE;
-- DROP TABLE IF EXISTS event_half_start CASCADE;

SELECT 'DROP TABLE IF EXISTS "' || table_name || '" CASCADE;' 
FROM information_schema.tables 
WHERE table_schema = 'public';
