// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface InjuryStoppage {
    id: string;
    index: number;
    period: number;
    timestamp: string;
    minute: number;
    second: number;
    type: Foreign;
    possession: number;
    possession_team: Foreign;
    play_pattern: Foreign;
    team: Foreign;
    player: Foreign;
    position: Foreign;
    duration: number;
    injury_stoppage: InjuryStoppageClass | null;
    off_camera: boolean;
    under_pressure: boolean;
    location: number[] | null;
}

export interface InjuryStoppageClass {
    in_chain: boolean;
}

export interface Foreign {
    id: number;
    name: string;
}
