// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface The15946 {
    team_id: number;
    team_name: string;
    lineup: Lineup[];
}

export interface Lineup {
    player_id: number;
    player_name: string;
    player_nickname: null | string;
    jersey_number: number;
    country: Country;
    cards: Card[];
    positions: Position[];
}

export interface Card {
    time: string;
    card_type: string;
    reason: string;
    period: number;
}

export interface Country {
    id: number;
    name: string;
}

export interface Position {
    position_id: number;
    position: string;
    from: string;
    to: null | string;
    from_period: number;
    to_period: number | null;
    start_reason: string;
    end_reason: string;
}
