// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface The44 {
    match_id: number;
    match_date: string;
    kick_off: string;
    competition: Competition;
    season: Season;
    home_team: HomeTeam;
    away_team: AwayTeam;
    home_score: number;
    away_score: number;
    match_status: string;
    match_status_360: string;
    last_updated: string;
    last_updated_360: string;
    match_week: number;
    competition_stage: Foreign;
    stadium?: Referee;
    referee?: Referee;
}

export interface AwayTeam {
    away_team_id: number;
    away_team_name: string;
    away_team_gender: string;
    away_team_group: null;
    country: Foreign;
    managers?: Manager[];
}

export interface Foreign {
    id: number;
    name: string;
}

export interface Manager {
    id: number;
    name: string;
    nickname: null | string;
    dob: string;
    country: Foreign;
}

export interface Competition {
    competition_id: number;
    country_name: string;
    competition_name: string;
}

export interface HomeTeam {
    home_team_id: number;
    home_team_name: string;
    home_team_gender: string;
    home_team_group: null;
    country: Foreign;
    managers?: Manager[];
}

export interface Referee {
    id: number;
    name: string;
    country: Foreign;
}

export interface Season {
    season_id: number;
    season_name: string;
}
