// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface Miscontrol {
    id: string;
    index: number;
    period: number;
    timestamp: string;
    minute: number;
    second: number;
    type: Foreign;
    possession: number;
    possession_team: Foreign;
    play_pattern: Foreign;
    team: Foreign;
    player: Foreign;
    position: Foreign;
    location: number[];
    duration: number;
    under_pressure: boolean;
    out: boolean;
    miscontrol: MiscontrolClass | null;
    off_camera: boolean;
}

export interface MiscontrolClass {
    aerial_won: boolean;
}

export interface Foreign {
    id: number;
    name: string;
}
