// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface Passes {
    id: string;
    index: number;
    period: number;
    timestamp: string;
    minute: number;
    second: number;
    type: Foreign;
    possession: number;
    possession_team: Foreign;
    play_pattern: Foreign;
    team: Foreign;
    player: Foreign;
    position: Foreign;
    location: number[];
    duration: number;
    pass: Pass;
    under_pressure: boolean;
    off_camera: boolean;
    counterpress: boolean;
    out: boolean;
}

export interface Pass {
    recipient: Foreign | null;
    length: number;
    angle: number;
    height: Foreign;
    end_location: number[];
    body_part: Foreign | null;
    type: Foreign | null;
    outcome: Foreign | null;
    aerial_won: boolean;
    assisted_shot_id: string | null;
    shot_assist: boolean;
    switch: boolean;
    cross: boolean;
    deflected: boolean;
    inswinging: boolean;
    technique: Foreign | null;
    through_ball: boolean;
    no_touch: boolean;
    outswinging: boolean;
    miscommunication: boolean;
    cut_back: boolean;
    goal_assist: boolean;
    straight: boolean;
}

export interface Foreign {
    id: number;
    name: Name;
}

export enum Name {
    AdriàGinerPedrosa = "Adrià Giner Pedrosa",
    AdriánLópezÁlvarez = "Adrián López Álvarez",
    AitorFernándezAbarisketa = "Aitor Fernández Abarisketa",
    AlfaSemedoEsteves = "Alfa Semedo Esteves",
    AnssumaneFati = "Anssumane Fati",
    AntoineGriezmann = "Antoine Griezmann",
    AntonioManuelLunaRodríguez = "Antonio Manuel Luna Rodríguez",
    AridaneHernándezUmpiérrez = "Aridane Hernández Umpiérrez",
    AritzElustondoIrribaria = "Aritz Elustondo Irribaria",
    ArthurHenriqueRamosDeOliveiraMelo = "Arthur Henrique Ramos de Oliveira Melo",
    ArturoErasmoVidalPardo = "Arturo Erasmo Vidal Pardo",
    AsierIllarramendiAndonegi = "Asier Illarramendi Andonegi",
    AtléticoMadrid = "Atlético Madrid",
    Barcelona = "Barcelona",
    BorjaIglesiasQuintas = "Borja Iglesias Quintas",
    BorjaMayoralMoya = "Borja Mayoral Moya",
    BrunoGonzálezCabrera = "Bruno González Cabrera",
    CarlosHenriqueCasimiro = "Carlos Henrique Casimiro",
    CenterAttackingMidfield = "Center Attacking Midfield",
    CenterBack = "Center Back",
    CenterDefensiveMidfield = "Center Defensive Midfield",
    CenterForward = "Center Forward",
    ClémentLenglet = "Clément Lenglet",
    Corner = "Corner",
    DanielCarvajalRamos = "Daniel Carvajal Ramos",
    DavidGarcíaZubiría = "David García Zubiría",
    DavidRemeseiroSalgueiro = "David Remeseiro Salgueiro",
    DavidZurutuzaVeillet = "David Zurutuza Veillet",
    DiegoDaSilvaCosta = "Diego da Silva Costa",
    DiegoLópezRodríguez = "Diego López Rodríguez",
    DropKick = "Drop Kick",
    EdinaldoGomesPereira = "Edinaldo Gomes Pereira",
    EnesÜnal = "Enes Ünal",
    EnisBardhi = "Enis Bardhi",
    EnriquePérezMuñoz = "Enrique Pérez Muñoz",
    Espanyol = "Espanyol",
    EstebanFélixGraneroMolina = "Esteban Félix Granero Molina",
    FedericoSANEmeterioDíaz = "Federico San Emeterio Díaz",
    FedericoSantiagoValverdeDipetta = "Federico Santiago Valverde Dipetta",
    FelipeAugustoDeAlmeidaMonteiro = "Felipe Augusto de Almeida Monteiro",
    FerlandMendy = "Ferland Mendy",
    FranciscoAntónioMachadoMotaDeCastroTrincão = "Francisco António Machado Mota de Castro Trincão",
    FranciscoJoséOlivasAlba = "Francisco José Olivas Alba",
    FranciscoRománAlarcónSuárez = "Francisco Román Alarcón Suárez",
    FreeKick = "Free Kick",
    FrenkieDeJong = "Frenkie de Jong",
    FromCorner = "From Corner",
    FromCounter = "From Counter",
    FromFreeKick = "From Free Kick",
    FromGoalKick = "From Goal Kick",
    FromKeeper = "From Keeper",
    FromKickOff = "From Kick Off",
    FromThrowIn = "From Throw In",
    GarethFrankBale = "Gareth Frank Bale",
    GerardPiquéBernabéu = "Gerard Piqué Bernabéu",
    GerónimoRulli = "Gerónimo Rulli",
    GoalKick = "Goal Kick",
    Goalkeeper = "Goalkeeper",
    GroundPass = "Ground Pass",
    Head = "Head",
    HighPass = "High Pass",
    HéctorAlfredoMorenoHerrera = "Héctor Alfredo Moreno Herrera",
    HéctorJuniorFirpoAdames = "Héctor Junior Firpo Adames",
    IgorZubeldiaElorza = "Igor Zubeldia Elorza",
    Incomplete = "Incomplete",
    InjuryClearance = "Injury Clearance",
    Inswinging = "Inswinging",
    Interception = "Interception",
    IvanRakitić = "Ivan Rakitić",
    JanOblak = "Jan Oblak",
    JavierMoyanoLujano = "Javier Moyano Lujano",
    JavierSánchezDeFelipe = "Javier Sánchez de Felipe",
    JoaquínFernándezMoreno = "Joaquín Fernández Moreno",
    JonBautistaOrgilles = "Jon Bautista Orgilles",
    JordiAlbaRamos = "Jordi Alba Ramos",
    JordiMasipLópez = "Jordi Masip López",
    JorgeAndújarMoreno = "Jorge Andújar Moreno",
    JosebaZaldúaBengoetxea = "Joseba Zaldúa Bengoetxea",
    JoséIgnacioFernándezIglesias = "José Ignacio Fernández Iglesias",
    JoséIgnacioMartínezGarcía = "José Ignacio Martínez García",
    JoséLuisMoralesNogales = "José Luis Morales Nogales",
    JoséManuelArnáizDíaz = "José Manuel Arnáiz Díaz",
    JoséMaríaGiménezDeVargas = "José María Giménez de Vargas",
    JoséÁngelGómezCampaña = "José Ángel Gómez Campaña",
    JoãoFélixSequeira = "João Félix Sequeira",
    JuanMiguelJiménezLópez = "Juan Miguel Jiménez López",
    KarimBenzema = "Karim Benzema",
    KeeperArm = "Keeper Arm",
    KenanKodro = "Kenan Kodro",
    KickOff = "Kick Off",
    LeftAttackingMidfield = "Left Attacking Midfield",
    LeftBack = "Left Back",
    LeftCenterBack = "Left Center Back",
    LeftCenterForward = "Left Center Forward",
    LeftCenterMidfield = "Left Center Midfield",
    LeftDefensiveMidfield = "Left Defensive Midfield",
    LeftFoot = "Left Foot",
    LeftMidfield = "Left Midfield",
    LeftWing = "Left Wing",
    LeftWingBack = "Left Wing Back",
    LeiWu = "Lei Wu",
    LevanteUD = "Levante UD",
    LionelAndrésMessiCuccittini = "Lionel Andrés Messi Cuccittini",
    LluísLópezMármol = "Lluís López Mármol",
    LowPass = "Low Pass",
    LucaSangalliFuentes = "Luca Sangalli Fuentes",
    LucasRenéOlazaCatrofe = "Lucas René Olaza Catrofe",
    LucasVázquezIglesias = "Lucas Vázquez Iglesias",
    LuisAlbertoSuárezDíaz = "Luis Alberto Suárez Díaz",
    LukaModrić = "Luka Modrić",
    MalcomFilipeSilvaDeOliveira = "Malcom Filipe Silva de Oliveira",
    MarcAndréTerStegen = "Marc-André ter Stegen",
    MarcRocaJunqué = "Marc Roca Junqué",
    MarceloVieiraDaSilvaJúnior = "Marcelo Vieira da Silva Júnior",
    MarcoAsensioWillemsen = "Marco Asensio Willemsen",
    MarcosAndréDeSousaMendonça = "Marcos André de Sousa Mendonça",
    MarcosLlorenteMoreno = "Marcos Llorente Moreno",
    MarianoDíazMejía = "Mariano Díaz Mejía",
    MarioHermosoCanseco = "Mario Hermoso Canseco",
    MartinBraithwaiteChristensen = "Martin Braithwaite Christensen",
    MikelMerinoZazón = "Mikel Merino Zazón",
    MikelOyarzabalUgarte = "Mikel Oyarzabal Ugarte",
    MoribaKouroumaKourouma = "Moriba Kourouma Kourouma",
    MosesDaddyAjalaSimon = "Moses Daddy-Ajala Simon",
    NikolaVukčević = "Nikola Vukčević",
    NoTouch = "No Touch",
    NorbertoMuraraNeto = "Norberto Murara Neto",
    NélsonCabralSemedo = "Nélson Cabral Semedo",
    Osasuna = "Osasuna",
    Other = "Other",
    OusmaneDembélé = "Ousmane Dembélé",
    Out = "Out",
    Outswinging = "Outswinging",
    PabloHervíasRuiz = "Pablo Hervías Ruiz",
    Pass = "Pass",
    PassOffside = "Pass Offside",
    PedroGonzálezLópez = "Pedro González López",
    PhilippeCoutinhoCorreia = "Philippe Coutinho Correia",
    RafaelAlcântaraDoNascimento = "Rafael Alcântara do Nascimento",
    RaphaëlVarane = "Raphaël Varane",
    RaúlGarcíaCarnero = "Raúl García Carnero",
    RaúlRodríguezNavas = "Raúl Rodríguez Navas",
    RealMadrid = "Real Madrid",
    RealSociedad = "Real Sociedad",
    RealValladolid = "Real Valladolid",
    Recovery = "Recovery",
    RegularPlay = "Regular Play",
    RenanAugustoLodiDOSSantos = "Renan Augusto Lodi dos Santos",
    RicardPuigMartí = "Ricard Puig Martí",
    RightAttackingMidfield = "Right Attacking Midfield",
    RightBack = "Right Back",
    RightCenterBack = "Right Center Back",
    RightCenterForward = "Right Center Forward",
    RightCenterMidfield = "Right Center Midfield",
    RightDefensiveMidfield = "Right Defensive Midfield",
    RightFoot = "Right Foot",
    RightMidfield = "Right Midfield",
    RightWing = "Right Wing",
    RightWingBack = "Right Wing Back",
    RobertoJoséRosalesAltuve = "Roberto José Rosales Altuve",
    RobertoSuárezPier = "Roberto Suárez Pier",
    RodrygoSilvaDeGoes = "Rodrygo Silva de Goes",
    RogerMartíSalvador = "Roger Martí Salvador",
    RonaldFedericoAraújoDaSilva = "Ronald Federico Araújo da Silva",
    RoqueMesaQuevedo = "Roque Mesa Quevedo",
    RubénAlcarazJiménez = "Rubén Alcaraz Jiménez",
    RubénPardoGutiérrez = "Rubén Pardo Gutiérrez",
    RubénRochinaNaixes = "Rubén Rochina Naixes",
    RúbenMiguelNunesVezo = "Rúben Miguel Nunes Vezo",
    SaidyJanko = "Saidy Janko",
    SamuelYvesUmtiti = "Samuel Yves Umtiti",
    SandroRamírezCastillo = "Sandro Ramírez Castillo",
    SantiagoAriasNaranjo = "Santiago Arias Naranjo",
    SaúlÑíguezEsclapez = "Saúl Ñíguez Esclapez",
    SergiRobertoCarnicer = "Sergi Roberto Carnicer",
    SerginoDest = "Sergino Dest",
    SergioBusquetsIBurgos = "Sergio Busquets i Burgos",
    SergioGarcíaDeLaFuente = "Sergio García De La Fuente",
    SergioGuardiolaNavarro = "Sergio Guardiola Navarro",
    SergioRamosGarcía = "Sergio Ramos García",
    SergioReguilónRodríguez = "Sergio Reguilón Rodríguez",
    Straight = "Straight",
    TheoBernardFrançoisHernández = "Theo Bernard François Hernández",
    ThibautCourtois = "Thibaut Courtois",
    ThomasLemar = "Thomas Lemar",
    ThomasTeyePartey = "Thomas Teye Partey",
    ThroughBall = "Through Ball",
    ThrowIn = "Throw-in",
    ToniKroos = "Toni Kroos",
    Unknown = "Unknown",
    ViníciusJoséPaixãoDeOliveiraJúnior = "Vinícius José Paixão de Oliveira Júnior",
    VíctorMachínPérez = "Víctor Machín Pérez",
    VíctorSánchezMata = "Víctor Sánchez Mata",
    WaldoRubioMartín = "Waldo Rubio Martín",
    YannickFerreiraCarrasco = "Yannick Ferreira Carrasco",
    ÁlvaroBorjaMorataMartín = "Álvaro Borja Morata Martín",
    ÁlvaroOdriozolaArzallus = "Álvaro Odriozola Arzallus",
    ÁngelMartínCorrea = "Ángel Martín Correa",
    ÉderGabrielMilitão = "Éder Gabriel Militão",
    ÓscarMelendoJiménez = "Óscar Melendo Jiménez",
    ÓscarMinguezaGarcía = "Óscar Mingueza García",
    ÓscarPlanoPedreño = "Óscar Plano Pedreño"
}
