// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface Shot {
    id: string;
    index: number;
    period: number;
    timestamp: string;
    minute: number;
    second: number;
    type: Foreign;
    possession: number;
    possession_team: Foreign;
    play_pattern: Foreign;
    team: Foreign;
    player: Foreign;
    position: Foreign;
    location: number[];
    duration: number;
    shot: ShotClass;
    under_pressure: boolean;
    out: boolean;
    off_camera: boolean;
}

export interface Foreign {
    id: number;
    name: string;
}

export interface ShotClass {
    statsbomb_xg: number;
    end_location: number[];
    key_pass_id: string | null;
    body_part: Foreign;
    type: Foreign;
    outcome: Foreign;
    first_time: boolean;
    technique: Foreign;
    freeze_frame: FreezeFrame[] | null;
    deflected: boolean;
    one_on_one: boolean;
    aerial_won: boolean;
    saved_to_post: boolean;
    redirect: boolean;
    open_goal: boolean;
    follows_dribble: boolean;
    saved_off_target: boolean;
}

export interface FreezeFrame {
    location: number[];
    player: Foreign;
    position: Foreign;
    teammate: boolean;
}
