// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface TacticalShift {
    id: string;
    index: number;
    period: number;
    timestamp: string;
    minute: number;
    second: number;
    type: Foreign;
    possession: number;
    possession_team: Foreign;
    play_pattern: Foreign;
    team: Foreign;
    duration: number;
    tactics: Tactics;
}

export interface Foreign {
    id: number;
    name: string;
}

export interface Tactics {
    formation: number;
    lineup: Lineup[];
}

export interface Lineup {
    player: Foreign;
    position: Foreign;
    jersey_number: number;
}
