// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface FoulCommitted {
    id: string;
    index: number;
    period: number;
    timestamp: string;
    minute: number;
    second: number;
    type: Foreign;
    possession: number;
    possession_team: Foreign;
    play_pattern: Foreign;
    team: Foreign;
    player: Foreign;
    position: Foreign;
    location: number[];
    duration: number;
    counterpress: boolean;
    foul_committed: FoulCommittedClass | null;
    off_camera: boolean;
    under_pressure: boolean;
}

export interface FoulCommittedClass {
    type: Foreign | null;
    penalty: boolean;
    advantage: boolean;
    card: Foreign | null;
    offensive: boolean;
}

export interface Foreign {
    id: number;
    name: string;
}
