// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface GoalKeeper {
    id: string;
    index: number;
    period: number;
    timestamp: string;
    minute: number;
    second: number;
    type: Foreign;
    possession: number;
    possession_team: Foreign;
    play_pattern: Foreign;
    team: Foreign;
    player: Foreign;
    position: Foreign;
    location: number[] | null;
    duration: number;
    goalkeeper: Goalkeeper;
    out: boolean;
    under_pressure: boolean;
    off_camera: boolean;
}

export interface Goalkeeper {
    outcome: Foreign | null;
    technique: Foreign | null;
    position: Foreign | null;
    body_part: Foreign | null;
    type: Foreign;
    end_location: number[] | null;
    shot_saved_to_post: boolean;
    punched_out: boolean;
    success_in_play: boolean;
    shot_saved_off_target: boolean;
    lost_out: boolean;
    lost_in_play: boolean;
}

export interface Foreign {
    id: number;
    name: Name;
}

export enum Name {
    AarónEscandellBanacloche = "Aarón Escandell Banacloche",
    AitorFernándezAbarisketa = "Aitor Fernández Abarisketa",
    AlejandroRemiroGargallo = "Alejandro Remiro Gargallo",
    AnttiMikkoNiemi = "Antti Mikko Niemi",
    Arsenal = "Arsenal",
    AsierRiesgoUnamuno = "Asier Riesgo Unamuno",
    AstonVilla = "Aston Villa",
    AthleticClub = "Athletic Club",
    AtléticoMadrid = "Atlético Madrid",
    AxelWerner = "Axel Werner",
    Barcelona = "Barcelona",
    BirminghamCity = "Birmingham City",
    BlackburnRovers = "Blackburn Rovers",
    BoltonWanderers = "Bolton Wanderers",
    BothHands = "Both Hands",
    BradFriedel = "Brad Friedel",
    CarloCudicini = "Carlo Cudicini",
    CeltaVigo = "Celta Vigo",
    CharltonAthletic = "Charlton Athletic",
    Chelsea = "Chelsea",
    Chest = "Chest",
    Claim = "Claim",
    ClaudioAndrésBravoMuñoz = "Claudio Andrés Bravo Muñoz",
    Clear = "Clear",
    Collected = "Collected",
    CollectedTwice = "Collected Twice",
    Cádiz = "Cádiz",
    DannyCoyne = "Danny Coyne",
    DavidJames = "David James",
    DavidSeaman = "David Seaman",
    DavidSoriaSolís = "David Soria Solís",
    DeanKiely = "Dean Kiely",
    DeportivoAlavés = "Deportivo Alavés",
    DiegoLópezRodríguez = "Diego López Rodríguez",
    Diving = "Diving",
    EdgarBadíaGuardiola = "Edgar Badía Guardiola",
    EdwinVanDerSar = "Edwin van der Sar",
    Eibar = "Eibar",
    Elche = "Elche",
    Espanyol = "Espanyol",
    Everton = "Everton",
    Fail = "Fail",
    FernandoPachecoFlores = "Fernando Pacheco Flores",
    FromCorner = "From Corner",
    FromCounter = "From Counter",
    FromFreeKick = "From Free Kick",
    FromGoalKick = "From Goal Kick",
    FromKeeper = "From Keeper",
    FromKickOff = "From Kick Off",
    FromThrowIn = "From Throw In",
    Fulham = "Fulham",
    GerónimoRulli = "Gerónimo Rulli",
    Getafe = "Getafe",
    Girona = "Girona",
    GoalConceded = "Goal Conceded",
    GoalKeeper = "Goal Keeper",
    Goalkeeper = "Goalkeeper",
    Granada = "Granada",
    Head = "Head",
    Huesca = "Huesca",
    IagoHerrerínBuisán = "Iago Herrerín Buisán",
    IanBennett = "Ian Bennett",
    IanWalker = "Ian Walker",
    InPlayDanger = "In Play Danger",
    InPlaySafe = "In Play Safe",
    IvánCuéllarSacristán = "Iván Cuéllar Sacristán",
    IvánVillarMartínez = "Iván Villar Martínez",
    JanOblak = "Jan Oblak",
    JasperCillessen = "Jasper Cillessen",
    JaumeDoménechSánchez = "Jaume Doménech Sánchez",
    JensLehmann = "Jens Lehmann",
    JeremíasLedesma = "Jeremías Ledesma",
    JerzyDudek = "Jerzy Dudek",
    JoelRoblesBlázquez = "Joel Robles Blázquez",
    JordiMasipLópez = "Jordi Masip López",
    JussiJääskeläinen = "Jussi Jääskeläinen",
    KaseyKeller = "Kasey Keller",
    KeeperSweeper = "Keeper Sweeper",
    LeedsUnited = "Leeds United",
    LeftFoot = "Left Foot",
    LeftHand = "Left Hand",
    Leganés = "Leganés",
    LeicesterCity = "Leicester City",
    LevanteUD = "Levante UD",
    Liverpool = "Liverpool",
    LostInPlay = "Lost In Play",
    LostOut = "Lost Out",
    MaikTaylor = "Maik Taylor",
    Mallorca = "Mallorca",
    ManchesterCity = "Manchester City",
    ManchesterUnited = "Manchester United",
    ManuelReinaRodríguez = "Manuel Reina Rodríguez",
    MarcAndréTerStegen = "Marc-André ter Stegen",
    MarkSchwarzer = "Mark Schwarzer",
    MarkoDmitrović = "Marko Dmitrović",
    MichaelOakes = "Michael Oakes",
    Middlesbrough = "Middlesbrough",
    Moving = "Moving",
    NeilSullivan = "Neil Sullivan",
    NewcastleUnited = "Newcastle United",
    NigelMartyn = "Nigel Martyn",
    NoTouch = "No Touch",
    NorbertoMuraraNeto = "Norberto Murara Neto",
    OierOlazábalParedes = "Oier Olazábal Paredes",
    Osasuna = "Osasuna",
    Other = "Other",
    PauLópezSabata = "Pau López Sabata",
    PaulJones = "Paul Jones",
    PaulRobinson = "Paul Robinson",
    PenaltyConceded = "Penalty Conceded",
    PenaltySaved = "Penalty Saved",
    Portsmouth = "Portsmouth",
    Prone = "Prone",
    Punch = "Punch",
    PunchedOut = "Punched out",
    RayoVallecano = "Rayo Vallecano",
    RealBetis = "Real Betis",
    RealMadrid = "Real Madrid",
    RealSociedad = "Real Sociedad",
    RealValladolid = "Real Valladolid",
    RegularPlay = "Regular Play",
    RichardWright = "Richard Wright",
    RightFoot = "Right Foot",
    RightHand = "Right Hand",
    RobertoJiménezGago = "Roberto Jiménez Gago",
    RoyCarroll = "Roy Carroll",
    RubénBlancoVeiga = "Rubén Blanco Veiga",
    RuiTiagoDantasDaSilva = "Rui Tiago Dantas da Silva",
    Save = "Save",
    SavedTwice = "Saved Twice",
    SergioAsenjoAndrés = "Sergio Asenjo Andrés",
    SergioHerreraPirón = "Sergio Herrera Pirón",
    Set = "Set",
    Sevilla = "Sevilla",
    ShakaHislop = "Shaka Hislop",
    ShayGiven = "Shay Given",
    ShotFaced = "Shot Faced",
    ShotSaved = "Shot Saved",
    ShotSavedOffTarget = "Shot Saved Off Target",
    ShotSavedToPost = "Shot Saved to Post",
    Smother = "Smother",
    Southampton = "Southampton",
    Standing = "Standing",
    StoleDimitrievski = "Stole Dimitrievski",
    Success = "Success",
    SuccessInPlay = "Success In Play",
    ThibautCourtois = "Thibaut Courtois",
    ThomasLøvendahlSørensen = "Thomas Løvendahl Sørensen",
    TimHoward = "Tim Howard",
    TomášVaclík = "Tomáš Vaclík",
    TottenhamHotspur = "Tottenham Hotspur",
    TouchedIn = "Touched In",
    TouchedOut = "Touched Out",
    UnaiSimónMendibil = "Unai Simón Mendibil",
    Valencia = "Valencia",
    Villarreal = "Villarreal",
    WolverhamptonWanderers = "Wolverhampton Wanderers",
    Won = "Won",
    YassineBounou = "Yassine Bounou",
    ÁlvaroFernándezLlorente = "Álvaro Fernández Llorente"
}
